api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title:  RECETTES API
    description:    Faldji
    version:    1.0.0
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
